/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_control.iconos;

import Servicios.ConexionDB;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author AMD RYZEN
 */
public class IDEAdmin extends javax.swing.JFrame {

    /**
     * Creates new form IDEInicio
     */
    DefaultTableModel model, model2;
    ConexionDB conexion = null;
    String seleccionar = null;

    public IDEAdmin(ConexionDB conexion) {
        initComponents();
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(false);
        this.PReabastecer.setVisible(false);
        this.HistorialCompras.setVisible(false);
        this.PReabastecer.setVisible(false);
        this.HistorialCompras.setVisible(false);
        this.PHistVentas.setVisible(false);
        this.PInventario.setVisible(false);
        this.conexion = conexion;
    }

    public IDEAdmin() {
        initComponents();
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(false);
        this.PReabastecer.setVisible(false);
        this.HistorialCompras.setVisible(false);
        this.conexion = conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Slider = new javax.swing.JPanel();
        Slide2 = new javax.swing.JLabel();
        Slide1 = new javax.swing.JLabel();
        Shop = new javax.swing.JPanel();
        BComprar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HistorialV = new javax.swing.JPanel();
        BHistorialVentas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Salir = new javax.swing.JPanel();
        BSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tAg2 = new javax.swing.JLabel();
        Inventario = new javax.swing.JPanel();
        BInventario = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        HistC = new javax.swing.JPanel();
        BHistorialCompras = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PReabastecer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TNombreArticulo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TCantidad = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        TEmpresa = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        TProveedor = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Iconos = new javax.swing.JLabel();
        HistorialCompras = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tHistorialCompras = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        PHistVentas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tHistorialVentas = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        PInventario = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tInventario = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        tAg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 191, 164));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(172, 191, 164));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Slider.setBackground(new java.awt.Color(249, 35, 61));
        Slider.setMaximumSize(new java.awt.Dimension(250, 480));

        Slide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide2.setAlignmentY(0.0F);
        Slide2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide2MouseClicked(evt);
            }
        });

        Slide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide1.setAlignmentY(0.0F);
        Slide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide1MouseClicked(evt);
            }
        });

        Shop.setBackground(new java.awt.Color(249, 35, 61));
        Shop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BComprar.setBackground(new java.awt.Color(72, 69, 112));
        BComprar.setBorder(null);
        BComprar.setBorderPainted(false);
        BComprar.setContentAreaFilled(false);
        BComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BComprarActionPerformed(evt);
            }
        });
        Shop.add(BComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel3.setBackground(new java.awt.Color(249, 35, 61));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_shopping_bag_black_24dp.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        Shop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, 46));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reabastecer");
        Shop.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, 104, -1));

        HistorialV.setBackground(new java.awt.Color(249, 35, 61));
        HistorialV.setPreferredSize(new java.awt.Dimension(0, 180));
        HistorialV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BHistorialVentas.setBackground(new java.awt.Color(133, 14, 74));
        BHistorialVentas.setBorder(null);
        BHistorialVentas.setBorderPainted(false);
        BHistorialVentas.setContentAreaFilled(false);
        BHistorialVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHistorialVentasActionPerformed(evt);
            }
        });
        HistorialV.add(BHistorialVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel4.setBackground(new java.awt.Color(249, 35, 61));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_article_black_24dp.png"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        HistorialV.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Historial ventas");
        HistorialV.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 15, 109, -1));

        Salir.setBackground(new java.awt.Color(249, 35, 61));
        Salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BSalir.setBackground(new java.awt.Color(133, 14, 74));
        BSalir.setBorder(null);
        BSalir.setBorderPainted(false);
        BSalir.setContentAreaFilled(false);
        BSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });
        Salir.add(BSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel5.setBackground(new java.awt.Color(249, 35, 61));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_logout_black_24dp.png"))); // NOI18N
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setOpaque(true);
        Salir.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salir");
        Salir.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 17, 101, -1));

        tAg2.setText("2021");

        Inventario.setBackground(new java.awt.Color(249, 35, 61));
        Inventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BInventario.setBackground(new java.awt.Color(72, 69, 112));
        BInventario.setBorder(null);
        BInventario.setBorderPainted(false);
        BInventario.setContentAreaFilled(false);
        BInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInventarioActionPerformed(evt);
            }
        });
        Inventario.add(BInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel11.setBackground(new java.awt.Color(249, 35, 61));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_store_black_24dp.png"))); // NOI18N
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setOpaque(true);
        Inventario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, 46));

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inventario");
        Inventario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, 104, -1));

        HistC.setBackground(new java.awt.Color(249, 35, 61));
        HistC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BHistorialCompras.setBackground(new java.awt.Color(72, 69, 112));
        BHistorialCompras.setBorder(null);
        BHistorialCompras.setBorderPainted(false);
        BHistorialCompras.setContentAreaFilled(false);
        BHistorialCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BHistorialCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHistorialComprasActionPerformed(evt);
            }
        });
        HistC.add(BHistorialCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel13.setBackground(new java.awt.Color(249, 35, 61));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_receipt_black_24dp.png"))); // NOI18N
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setOpaque(true);
        HistC.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 46));

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Historial compras");
        HistC.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, 110, -1));

        javax.swing.GroupLayout SliderLayout = new javax.swing.GroupLayout(Slider);
        Slider.setLayout(SliderLayout);
        SliderLayout.setHorizontalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Shop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Slide2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(SliderLayout.createSequentialGroup()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HistorialV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SliderLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(tAg2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HistC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SliderLayout.setVerticalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Slide1)
                    .addComponent(Slide2))
                .addGap(31, 31, 31)
                .addComponent(Shop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(HistC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HistorialV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(tAg2)
                .addGap(32, 32, 32))
        );

        jPanel2.add(Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 480));

        PReabastecer.setBackground(new java.awt.Color(39, 156, 107));

        jPanel3.setBackground(new java.awt.Color(4, 175, 63));

        jLabel10.setBackground(new java.awt.Color(101, 47, 72));
        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Articulo");

        TNombreArticulo.setBackground(new java.awt.Color(255, 255, 255));
        TNombreArticulo.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(93, 93, 93))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(58, 87, 67));

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jButton1.setText("Comprar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(4, 175, 63));

        jLabel16.setBackground(new java.awt.Color(101, 47, 72));
        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Cantidad");

        TCantidad.setBackground(new java.awt.Color(255, 255, 255));
        TCantidad.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(95, 95, 95))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(4, 175, 63));

        jLabel18.setBackground(new java.awt.Color(101, 47, 72));
        jLabel18.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Nombre Empresa");

        TEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        TEmpresa.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(66, 66, 66))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(4, 175, 63));

        jLabel19.setBackground(new java.awt.Color(101, 47, 72));
        jLabel19.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("Proveedor");

        TProveedor.setBackground(new java.awt.Color(255, 255, 255));
        TProveedor.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(95, 95, 95))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PReabastecerLayout = new javax.swing.GroupLayout(PReabastecer);
        PReabastecer.setLayout(PReabastecerLayout);
        PReabastecerLayout.setHorizontalGroup(
            PReabastecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PReabastecerLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PReabastecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PReabastecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PReabastecerLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        PReabastecerLayout.setVerticalGroup(
            PReabastecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PReabastecerLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PReabastecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PReabastecerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PReabastecerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel2.add(PReabastecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        jPanel6.setBackground(new java.awt.Color(4, 175, 63));

        jLabel2.setBackground(new java.awt.Color(255, 141, 89));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TelStore");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(389, 389, 389))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        Iconos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iconos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/Captura de pantalla 2021-10-17 163124.png"))); // NOI18N
        Iconos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(Iconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 190));

        HistorialCompras.setBackground(new java.awt.Color(255, 141, 51));
        HistorialCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tHistorialCompras.setBackground(new java.awt.Color(245, 93, 62));
        tHistorialCompras.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tHistorialCompras.setForeground(new java.awt.Color(0, 0, 0));
        tHistorialCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tHistorialCompras);

        HistorialCompras.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 630, 170));

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Historial de compras");
        HistorialCompras.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel2.add(HistorialCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        PHistVentas.setBackground(new java.awt.Color(25, 29, 32));
        PHistVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tHistorialVentas.setBackground(new java.awt.Color(255, 255, 255));
        tHistorialVentas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tHistorialVentas.setForeground(new java.awt.Color(0, 0, 0));
        tHistorialVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tHistorialVentas);

        PHistVentas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 630, 170));

        jLabel20.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(4, 175, 63));
        jLabel20.setText("Historial de Ventas");
        PHistVentas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jPanel2.add(PHistVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        PInventario.setBackground(new java.awt.Color(25, 29, 32));
        PInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tInventario.setBackground(new java.awt.Color(255, 255, 255));
        tInventario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tInventario.setForeground(new java.awt.Color(0, 0, 0));
        tInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tInventario);

        PInventario.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 630, 170));

        jLabel21.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(4, 175, 63));
        jLabel21.setText("Inventario TelStore");
        PInventario.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jPanel2.add(PInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/54TLbcUcnRm3sWQK3HKkuAMedF1JSX7yKgEqYjnyTKPwrcPxaDznYPU1p1QGrNrvQdTdCECy2ByUFBHCZuUkz1ZRK27oJUsu65c1nLv4hqL6r9YTuBWGVUwPJjmHVoJhumNH4SCaA.jpg"))); // NOI18N
        icono.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        tAg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tAg.setText("Programacion Aplicada\n");
        tAg.setAlignmentX(0.5F);
        jPanel2.add(tAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Slide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide1MouseClicked
        this.Slider.setSize(230, 480);
        this.Slide2.setLocation(156, 6);
        Dimension sitio = this.Slider.getSize();
        if (this.Slider.getSize().height == 480 && this.Slider.getSize().width == 230) {
            this.Slide2.setVisible(true);
            this.Slide1.setLocation(6, 6);
            this.Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/sliderin.png")));
            if (Slide2.isVisible()) {
                this.Shop.setVisible(true);
            }

        }
    }//GEN-LAST:event_Slide1MouseClicked

    private void Slide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide2MouseClicked
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(true);
    }//GEN-LAST:event_Slide2MouseClicked

    private void BComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BComprarActionPerformed
        this.PReabastecer.setVisible(true);
        this.HistorialCompras.setVisible(false);
        this.PHistVentas.setVisible(false);
        this.PInventario.setVisible(false);
    }//GEN-LAST:event_BComprarActionPerformed

    private void LlenarInventario() {
        ResultSet s = null;
        String[] titulos = {"Equipo", "Cantidad"};
        model = new DefaultTableModel(null, titulos);
        this.tInventario.setModel(model);
        s = conexion.consultarBD("SELECT*FROM tbl_equipos");
        try {
            while (s.next()) {
                Object[] Catalogo = {s.getString("Nombre_equipo"), s.getString("cantidad")};
                model.addRow(Catalogo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IDECliente1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LlenarHistorialVentas() {
        ResultSet s = null;
        String[] titulos = {"ID venta", "NIT", "Cantidad", "Fecha","Articulo","Id Articulo","Nombre Cliente","Valor unitario","Valor total","Vendedor"};
        model2 = new DefaultTableModel(null, titulos);
        this.tHistorialVentas.setModel(model2);
        s = conexion.consultarBD("SELECT*FROM tbl_venta_equipo");
        try {
            while (s.next()) {
                Object[] Catalogo = {s.getString("codigo_equipo_venta"), s.getString("fk_NIT"), s.getString("cantidad"), s.getString("fecha"),s.getString("nom_eq_ven"), s.getString("id"), s.getString("nom_cliente"),s.getString("valor_ind"), s.getString("total_venta"),s.getString("vendedor")};
                model2.addRow(Catalogo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IDEAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void BHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHistorialVentasActionPerformed
        this.PReabastecer.setVisible(false);
        this.HistorialCompras.setVisible(false);
        this.PHistVentas.setVisible(true);
        this.PInventario.setVisible(false);
        this.LlenarHistorialVentas();
    }//GEN-LAST:event_BHistorialVentasActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        conexion.CerrarConexion();
        this.setVisible(false);
        new IDEInicio().setVisible(true);
    }//GEN-LAST:event_BSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet ConsultaInventario = null;
        ResultSet RS = null;
        String NombreArticulo = this.TNombreArticulo.getText().toUpperCase();
        int Cantidad = Integer.parseInt(this.TCantidad.getText());
        String Empresa = this.TEmpresa.getText();
        String Proveedor = this.TProveedor.getText();
        int RArt = 0;
        int RCant = 0;
        boolean Result = false;
        double Valor = Math.random() * 3000000 + 150000;
        int FK_Compra = 0;
        int FK_Registro = 0;
        //Consulta en Inventario de la existencia de producto
        ConsultaInventario = conexion.consultarBD("SELECT Código_Equipo,cantidad FROM tbl_equipos WHERE UPPER(Nombre_Equipo) = '" + NombreArticulo + "'");
        try {
            while (ConsultaInventario.next()) {
                RArt = Integer.parseInt(ConsultaInventario.getString("Código_Equipo"));
                RCant = Integer.parseInt(ConsultaInventario.getString("cantidad"));
                Result = true;
            }
            if (!Result) {
                conexion.modificarBD("INSERT INTO tbl_equipos(Codigo_Inventario, Nombre_equipo, cantidad) VALUES (" + 1 + "," + "'" + NombreArticulo + "'" + "," + Cantidad + ")");
                conexion.modificarBD("INSERT INTO tbl_compra_equipo(Cantidad,Comprador,Nom_eq,Fecha,Valor_Unit,Valor_Total) VALUES (" + Cantidad + "," + "'" + Empresa + "'" + "," + "'" + NombreArticulo + "'" + "," + "'" + java.time.LocalDate.now() + "'" + "," + Valor + "," + Valor * Cantidad + ")");
                RS = conexion.consultarBD("SELECT MAX(Codigo_Equipo_Compra) AS ID FROM tbl_compra_equipo");
                while (RS.next()) {
                    FK_Compra = Integer.parseInt(RS.getString("ID"));
                }
                RS = conexion.consultarBD("SELECT MAX(Id_Factura_Compra) AS D FROM tbl_registro_compra");
                while(RS.next()){
                    FK_Registro = Integer.parseInt(RS.getString("D"));
                }
                conexion.modificarBD("INSERT INTO tbl_realizar_compra(Codigo_Equipo_Compra,Comprador,Proveedor,fk_NIT) VALUES (" + "'" + FK_Compra + "'" + "," + "'" + Empresa + "'" + "," + "'" + Proveedor + "'" + "," + "'" + 2222 + "'" + ")");
                conexion.modificarBD("INSERT INTO tbl_registro_compra(Cantidad,Valor_Unit,Valor_Total) VALUES(" + Cantidad + "," + Valor + "," + Cantidad * Valor + ")");
                conexion.modificarBD("INSERT INTO tbl_consulta_compra(Codigo_Equipo_Compra,Id_Factura_Compra) VALUES("+FK_Compra+","+FK_Registro+")");
                JOptionPane.showMessageDialog(this, "Tu compra ha sido exitosa", "compra", 1);
            } else {
                conexion.modificarBD("UPDATE tbl_equipos SET cantidad = " + (Cantidad + RCant) + " WHERE Código_Equipo = " + RArt);
                conexion.modificarBD("INSERT INTO tbl_compra_equipo(Cantidad,Comprador,Nom_eq,Fecha,Valor_Unit,Valor_Total) VALUES (" + Cantidad + "," + "'" + Empresa + "'" + "," + "'" + NombreArticulo + "'" + "," + "'" + java.time.LocalDate.now() + "'" + "," + Valor + "," + Valor * Cantidad + ")");

                RS = conexion.consultarBD("SELECT MAX(Codigo_Equipo_Compra) AS ID FROM tbl_compra_equipo");
                while (RS.next()) {
                    FK_Compra = Integer.parseInt(RS.getString("ID"));
                }
                RS = conexion.consultarBD("SELECT MAX(Id_Factura_Compra) AS D FROM tbl_registro_compra");
                while(RS.next()){
                    FK_Registro = Integer.parseInt(RS.getString("D"));
                }
                conexion.modificarBD("INSERT INTO tbl_realizar_compra(Codigo_Equipo_Compra,Comprador,Proveedor,fk_NIT) VALUES (" + "'" + FK_Compra + "'" + "," + "'" + Empresa + "'" + "," + "'" + Proveedor + "'" + "," + "'" + 2222 + "'" + ")");
                conexion.modificarBD("INSERT INTO tbl_registro_compra(Cantidad,Valor_Unit,Valor_Total) VALUES(" + Cantidad + "," + Valor + "," + Cantidad * Valor + ")");
                conexion.modificarBD("INSERT INTO tbl_consulta_compra(Codigo_Equipo_Compra,Id_Factura_Compra) VALUES("+FK_Compra+","+FK_Registro+")");
                JOptionPane.showMessageDialog(this, "Tu compra ha sido exitosa", "compra", 1);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void LlenarHC(){
        ResultSet s = null;
        String[] titulos = {"Id Compra", "Cantidad","Comprador","Articulo","Fecha","Valor Unitario","Valor total"};
        model2 = new DefaultTableModel(null, titulos);
        this.tHistorialCompras.setModel(model2);
        s = conexion.consultarBD("SELECT*FROM tbl_compra_equipo");
        try {
            while (s.next()) {
                Object[] Catalogo = {s.getString("Codigo_Equipo_Compra"), s.getString("Cantidad"),s.getString("Comprador"),s.getString("Nom_eq"),s.getString("Fecha"),s.getString("Valor_Unit"),s.getString("Valor_Total")};
                model2.addRow(Catalogo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IDECliente1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void BInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInventarioActionPerformed
       this.PInventario.setVisible(true);
       this.HistorialCompras.setVisible(false);
       this.PReabastecer.setVisible(false);
       this.PHistVentas.setVisible(false);
       this.LlenarInventario();
    }//GEN-LAST:event_BInventarioActionPerformed

    private void BHistorialComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHistorialComprasActionPerformed
        this.HistorialCompras.setVisible(true);
        this.PReabastecer.setVisible(false);
        this.PHistVentas.setVisible(false);
        this.PInventario.setVisible(false);
        this.LlenarHC();
    }//GEN-LAST:event_BHistorialComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDEAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDEAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDEAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDEAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDEAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComprar;
    private javax.swing.JButton BHistorialCompras;
    private javax.swing.JButton BHistorialVentas;
    private javax.swing.JButton BInventario;
    private javax.swing.JButton BSalir;
    private javax.swing.JPanel HistC;
    private javax.swing.JPanel HistorialCompras;
    private javax.swing.JPanel HistorialV;
    private javax.swing.JLabel Iconos;
    private javax.swing.JPanel Inventario;
    private javax.swing.JPanel PHistVentas;
    private javax.swing.JPanel PInventario;
    private javax.swing.JPanel PReabastecer;
    private javax.swing.JPanel Salir;
    private javax.swing.JPanel Shop;
    private javax.swing.JLabel Slide1;
    private javax.swing.JLabel Slide2;
    private javax.swing.JPanel Slider;
    private javax.swing.JTextField TCantidad;
    private javax.swing.JTextField TEmpresa;
    private javax.swing.JTextField TNombreArticulo;
    private javax.swing.JTextField TProveedor;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel tAg;
    private javax.swing.JLabel tAg2;
    private javax.swing.JTable tHistorialCompras;
    private javax.swing.JTable tHistorialVentas;
    private javax.swing.JTable tInventario;
    // End of variables declaration//GEN-END:variables

}
