/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_control.iconos;

import Servicios.ConexionDB;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author AMD RYZEN
 */
public class IDECliente1 extends javax.swing.JFrame {

    /**
     * Creates new form IDEInicio
     */
    DefaultTableModel model,model2;
    ConexionDB conexion = null;
    String seleccionar = null;

    public IDECliente1(ConexionDB conexion) {
        initComponents();
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(false);
        this.PCatalogo.setVisible(false);
        this.History.setVisible(false);
        this.conexion = conexion;
    }

    public IDECliente1() {
        initComponents();
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(false);
        this.PCatalogo.setVisible(false);
        this.History.setVisible(false);
        this.conexion = conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Slider = new javax.swing.JPanel();
        Slide2 = new javax.swing.JLabel();
        Slide1 = new javax.swing.JLabel();
        Shop = new javax.swing.JPanel();
        BComprar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Historial = new javax.swing.JPanel();
        BHistorial = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Salir = new javax.swing.JPanel();
        BSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tAg2 = new javax.swing.JLabel();
        PCatalogo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCatalogo = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        TArticulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TCantidad = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        TNombre_Client = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Iconos = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tHistorial = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        tAg = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 191, 164));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(172, 191, 164));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Slider.setBackground(new java.awt.Color(38, 40, 78));
        Slider.setMaximumSize(new java.awt.Dimension(250, 480));

        Slide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide2.setAlignmentY(0.0F);
        Slide2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide2MouseClicked(evt);
            }
        });

        Slide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide1.setAlignmentY(0.0F);
        Slide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide1MouseClicked(evt);
            }
        });

        Shop.setBackground(new java.awt.Color(72, 69, 112));
        Shop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BComprar.setBackground(new java.awt.Color(72, 69, 112));
        BComprar.setBorder(null);
        BComprar.setBorderPainted(false);
        BComprar.setContentAreaFilled(false);
        BComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BComprarActionPerformed(evt);
            }
        });
        Shop.add(BComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel3.setBackground(new java.awt.Color(72, 69, 112));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_shopping_bag_black_24dp.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        Shop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, 46));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Comprar");
        Shop.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, 104, -1));

        Historial.setBackground(new java.awt.Color(72, 69, 112));
        Historial.setPreferredSize(new java.awt.Dimension(0, 180));
        Historial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BHistorial.setBackground(new java.awt.Color(133, 14, 74));
        BHistorial.setBorder(null);
        BHistorial.setBorderPainted(false);
        BHistorial.setContentAreaFilled(false);
        BHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHistorialActionPerformed(evt);
            }
        });
        Historial.add(BHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel4.setBackground(new java.awt.Color(72, 69, 112));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_article_black_24dp.png"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        Historial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Historial ");
        Historial.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 15, 109, -1));

        Salir.setBackground(new java.awt.Color(72, 69, 112));
        Salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BSalir.setBackground(new java.awt.Color(133, 14, 74));
        BSalir.setBorder(null);
        BSalir.setBorderPainted(false);
        BSalir.setContentAreaFilled(false);
        BSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });
        Salir.add(BSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel5.setBackground(new java.awt.Color(72, 69, 112));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_logout_black_24dp.png"))); // NOI18N
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setOpaque(true);
        Salir.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salir");
        Salir.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 17, 101, -1));

        tAg2.setText("2021");

        javax.swing.GroupLayout SliderLayout = new javax.swing.GroupLayout(Slider);
        Slider.setLayout(SliderLayout);
        SliderLayout.setHorizontalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Shop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Slide2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(SliderLayout.createSequentialGroup()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Historial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SliderLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(tAg2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SliderLayout.setVerticalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Slide1)
                    .addComponent(Slide2))
                .addGap(31, 31, 31)
                .addComponent(Shop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(tAg2)
                .addGap(32, 32, 32))
        );

        jPanel2.add(Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 480));

        PCatalogo.setBackground(new java.awt.Color(101, 47, 72));

        TbCatalogo.setBackground(new java.awt.Color(202, 102, 86));
        TbCatalogo.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        TbCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Equipo", "ID"
            }
        ));
        TbCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TbCatalogoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TbCatalogoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TbCatalogo);

        jPanel1.setBackground(new java.awt.Color(250, 192, 94));

        TArticulo.setBackground(new java.awt.Color(250, 192, 94));
        TArticulo.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        TArticulo.setForeground(new java.awt.Color(51, 0, 51));
        TArticulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TArticulo.setText("Articulo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(59, 112, 128));

        jLabel10.setBackground(new java.awt.Color(101, 47, 72));
        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Cantidad:");

        TCantidad.setBackground(new java.awt.Color(255, 255, 255));
        TCantidad.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(93, 93, 93))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(58, 87, 67));

        jButton1.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jButton1.setText("Comprar");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(59, 112, 128));

        jLabel16.setBackground(new java.awt.Color(101, 47, 72));
        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Nombre:");

        TNombre_Client.setBackground(new java.awt.Color(255, 255, 255));
        TNombre_Client.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(TNombre_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(95, 95, 95))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNombre_Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PCatalogoLayout = new javax.swing.GroupLayout(PCatalogo);
        PCatalogo.setLayout(PCatalogoLayout);
        PCatalogoLayout.setHorizontalGroup(
            PCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCatalogoLayout.createSequentialGroup()
                .addGroup(PCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PCatalogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                    .addGroup(PCatalogoLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(PCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PCatalogoLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PCatalogoLayout.setVerticalGroup(
            PCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.add(PCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        jPanel6.setBackground(new java.awt.Color(101, 47, 72));

        jLabel2.setBackground(new java.awt.Color(255, 141, 89));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TelStore");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(389, 389, 389))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        Iconos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iconos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/Captura de pantalla 2021-10-17 163124.png"))); // NOI18N
        Iconos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(Iconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 190));

        History.setBackground(new java.awt.Color(255, 141, 51));
        History.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tHistorial.setBackground(new java.awt.Color(245, 93, 62));
        tHistorial.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tHistorial.setForeground(new java.awt.Color(0, 0, 0));
        tHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tHistorial);

        History.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 630, 170));

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Historial de compras");
        History.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel2.add(History, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/maxresdefault.jpg"))); // NOI18N
        jPanel2.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        tAg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tAg.setText("Programacion Aplicada\n");
        tAg.setAlignmentX(0.5F);
        jPanel2.add(tAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 26));

        jPanel5.setBackground(new java.awt.Color(252, 236, 82));
        jPanel5.setForeground(new java.awt.Color(252, 236, 82));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("jLabel9");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 180, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Slide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide1MouseClicked
        this.Slider.setSize(230, 480);
        this.Slide2.setLocation(156, 6);
        Dimension sitio = this.Slider.getSize();
        if (this.Slider.getSize().height == 480 && this.Slider.getSize().width == 230) {
            this.Slide2.setVisible(true);
            this.Slide1.setLocation(6, 6);
            this.Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/sliderin.png")));
            if (Slide2.isVisible()) {
                this.Shop.setVisible(true);
            }

        }
    }//GEN-LAST:event_Slide1MouseClicked

    private void Slide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide2MouseClicked
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(true);
    }//GEN-LAST:event_Slide2MouseClicked

    private void BComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BComprarActionPerformed
        this.PCatalogo.setVisible(true);
        this.LlenarCatalogo();
    }//GEN-LAST:event_BComprarActionPerformed

    private void LlenarCatalogo() {
        ResultSet s = null;
        String[] titulos = {"Equipo", "Cantidad disponible"};
        model = new DefaultTableModel(null, titulos);
        this.TbCatalogo.setModel(model);
        s = conexion.consultarBD("SELECT*FROM tbl_equipos");
        try {
            while (s.next()) {
                Object[] Catalogo = {s.getString("Nombre_equipo"), s.getString("cantidad")};
                model.addRow(Catalogo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IDECliente1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     private void LlenarHistorial() {
        ResultSet s = null;
        String[] titulos = {"Id Factura", "Cantidad","Valor unitario","Precio total"};
        model2 = new DefaultTableModel(null, titulos);
        this.tHistorial.setModel(model2);
        s = conexion.consultarBD("SELECT*FROM tbl_almacen_venta");
        try {
            while (s.next()) {
                Object[] Catalogo = {s.getString("ID_Factura_Venta"), s.getString("Cantidad"),s.getString("Valor_ind"),s.getString("Total_Venta")};
                model2.addRow(Catalogo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IDECliente1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void BHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHistorialActionPerformed
        this.PCatalogo.setVisible(false);
        this.History.setVisible(true);
        this.LlenarHistorial();
    }//GEN-LAST:event_BHistorialActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        conexion.CerrarConexion();
        this.setVisible(false);
        new IDEInicio().setVisible(true);
    }//GEN-LAST:event_BSalirActionPerformed

    private void TbCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCatalogoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TbCatalogoMouseEntered

    private void TbCatalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCatalogoMousePressed
        seleccionar = (String) this.TbCatalogo.getValueAt(TbCatalogo.getSelectedRow(), TbCatalogo.getSelectedColumn());
        this.TArticulo.setText(seleccionar);

    }//GEN-LAST:event_TbCatalogoMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet Primary_Name = null;
        String Primary_Key = null;
        String cantidad = null;
        int cant = 0;
        int quantity = 0;
        int PK;
        int FK_Inven = 0;
        double Precio = Math.random() * 3000000 + 150000;
        Primary_Name = conexion.consultarBD("SELECT Código_Equipo,cantidad,Codigo_Inventario from tbl_equipos where Nombre_Equipo =" + "'" + seleccionar + "'");
        try {
            while (Primary_Name.next()) {
                Primary_Key = Primary_Name.getString("Código_Equipo");
                cantidad = Primary_Name.getString("cantidad");
                FK_Inven = Integer.parseInt(Primary_Name.getString("Codigo_Inventario"));
                System.out.println(Primary_Key);
                System.out.println(cantidad);
            }
            cant = Integer.parseInt(cantidad);
            quantity = Integer.parseInt(cantidad);
            cant = cant - Integer.parseInt(this.TCantidad.getText());
            PK = Integer.parseInt(Primary_Key);
            conexion.modificarBD("UPDATE tbl_equipos SET cantidad=" + cant + " WHERE Código_Equipo=" + PK);
            conexion.modificarBD("INSERT INTO tbl_venta_equipo (cantidad,fecha,nom_eq_ven,id,nom_cliente,valor_ind,total_venta,vendedor,fk_Cod_Inventario)"
                    + " VALUES" + "(" + quantity + "," + "'" + java.time.LocalDate.now() + "'" + "," + "'" + seleccionar + "'" + "," + Primary_Key + "," + "'" + this.TNombre_Client.getText() + "'" + "," + Precio + "," + quantity * Precio + "," + "'" + "TelStore" + "'" + "," + FK_Inven + ")");
            conexion.modificarBD("INSERT INTO tbl_almacen_venta(Cantidad,Valor_ind,Total_Venta) VALUES("+quantity+","+Precio+","+quantity*Precio+")");
            JOptionPane.showMessageDialog(this, "Tu compra ha sido exitosa", "compra", 1);
        } catch (SQLException ex) {
            Logger.getLogger(IDECliente1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDECliente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComprar;
    private javax.swing.JButton BHistorial;
    private javax.swing.JButton BSalir;
    private javax.swing.JPanel Historial;
    private javax.swing.JPanel History;
    private javax.swing.JLabel Iconos;
    private javax.swing.JPanel PCatalogo;
    private javax.swing.JPanel Salir;
    private javax.swing.JPanel Shop;
    private javax.swing.JLabel Slide1;
    private javax.swing.JLabel Slide2;
    private javax.swing.JPanel Slider;
    private javax.swing.JLabel TArticulo;
    private javax.swing.JTextField TCantidad;
    private javax.swing.JTextField TNombre_Client;
    private javax.swing.JTable TbCatalogo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tAg;
    private javax.swing.JLabel tAg2;
    private javax.swing.JTable tHistorial;
    // End of variables declaration//GEN-END:variables

}
