/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_control.iconos;

import Servicios.ConexionDB;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AMD RYZEN
 */
public class IDECliente1 extends javax.swing.JFrame {

    /**
     * Creates new form IDEInicio
     */
    DefaultTableModel model;
    ConexionDB conexion = null;
    public IDECliente1(ConexionDB conexion) {
        initComponents();
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(false);
        this.PCatalogo.setVisible(false);
        this.PAcerca.setVisible(false);
        this.conexion =  conexion;
    }
    
    public IDECliente1() {
        initComponents();
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(false);
        this.PCatalogo.setVisible(false);
        this.PAcerca.setVisible(false);
        this.conexion =  conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Slider = new javax.swing.JPanel();
        Slide2 = new javax.swing.JLabel();
        Slide1 = new javax.swing.JLabel();
        Shop = new javax.swing.JPanel();
        BComprar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Historial = new javax.swing.JPanel();
        BHistorial = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Salir = new javax.swing.JPanel();
        BSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tAg2 = new javax.swing.JLabel();
        PCatalogo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCatalogo = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Iconos = new javax.swing.JLabel();
        PAcerca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        tAg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 191, 164));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(172, 191, 164));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Slider.setBackground(new java.awt.Color(38, 40, 78));
        Slider.setMaximumSize(new java.awt.Dimension(250, 480));

        Slide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide2.setAlignmentY(0.0F);
        Slide2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide2MouseClicked(evt);
            }
        });

        Slide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide1.setAlignmentY(0.0F);
        Slide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide1MouseClicked(evt);
            }
        });

        Shop.setBackground(new java.awt.Color(72, 69, 112));
        Shop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BComprar.setBackground(new java.awt.Color(72, 69, 112));
        BComprar.setBorder(null);
        BComprar.setBorderPainted(false);
        BComprar.setContentAreaFilled(false);
        BComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BComprarActionPerformed(evt);
            }
        });
        Shop.add(BComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel3.setBackground(new java.awt.Color(72, 69, 112));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_shopping_bag_black_24dp.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        Shop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, 46));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Acerca de");
        Shop.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, 104, -1));

        Historial.setBackground(new java.awt.Color(72, 69, 112));
        Historial.setPreferredSize(new java.awt.Dimension(0, 180));
        Historial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BHistorial.setBackground(new java.awt.Color(133, 14, 74));
        BHistorial.setBorder(null);
        BHistorial.setBorderPainted(false);
        BHistorial.setContentAreaFilled(false);
        BHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHistorialActionPerformed(evt);
            }
        });
        Historial.add(BHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel4.setBackground(new java.awt.Color(72, 69, 112));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_article_black_24dp.png"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        Historial.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cliente");
        Historial.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 15, 109, -1));

        Salir.setBackground(new java.awt.Color(72, 69, 112));
        Salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BSalir.setBackground(new java.awt.Color(133, 14, 74));
        BSalir.setBorder(null);
        BSalir.setBorderPainted(false);
        BSalir.setContentAreaFilled(false);
        BSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });
        Salir.add(BSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel5.setBackground(new java.awt.Color(72, 69, 112));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_logout_black_24dp.png"))); // NOI18N
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setOpaque(true);
        Salir.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Administrador");
        Salir.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 17, 101, -1));

        tAg2.setText("2021");

        javax.swing.GroupLayout SliderLayout = new javax.swing.GroupLayout(Slider);
        Slider.setLayout(SliderLayout);
        SliderLayout.setHorizontalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Shop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Slide2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(SliderLayout.createSequentialGroup()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Historial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SliderLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(tAg2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SliderLayout.setVerticalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Slide1)
                    .addComponent(Slide2))
                .addGap(31, 31, 31)
                .addComponent(Shop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Historial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(tAg2)
                .addGap(32, 32, 32))
        );

        jPanel2.add(Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 480));

        PCatalogo.setBackground(new java.awt.Color(101, 47, 72));

        TbCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Equipo", "ID"
            }
        ));
        jScrollPane1.setViewportView(TbCatalogo);

        javax.swing.GroupLayout PCatalogoLayout = new javax.swing.GroupLayout(PCatalogo);
        PCatalogo.setLayout(PCatalogoLayout);
        PCatalogoLayout.setHorizontalGroup(
            PCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        PCatalogoLayout.setVerticalGroup(
            PCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jPanel2.add(PCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        jPanel6.setBackground(new java.awt.Color(101, 47, 72));

        jLabel2.setBackground(new java.awt.Color(255, 141, 89));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TelStore");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(389, 389, 389))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        Iconos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iconos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/Captura de pantalla 2021-10-17 163124.png"))); // NOI18N
        Iconos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(Iconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 190));

        PAcerca.setBackground(new java.awt.Color(255, 141, 51));
        PAcerca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_info_white_24dp.png"))); // NOI18N
        PAcerca.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 39, 84, 58));

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Programa creado por:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 115, 510, -1));

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Steven Buritica");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 202, 510, -1));

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nicolas Cedeño");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 247, 510, -1));

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Killiam Puentes");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 292, 510, -1));

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Programacion Aplicada 2021");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 399, 510, -1));

        jPanel2.add(PAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/maxresdefault.jpg"))); // NOI18N
        jPanel2.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        tAg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tAg.setText("Programacion Aplicada\n");
        tAg.setAlignmentX(0.5F);
        jPanel2.add(tAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Slide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide1MouseClicked
       this.Slider.setSize(230, 480);
       this.Slide2.setLocation(156, 6);
       Dimension sitio = this.Slider.getSize();
       if(this.Slider.getSize().height == 480 && this.Slider.getSize().width == 230){
           this.Slide2.setVisible(true);
           this.Slide1.setLocation(6, 6);
           this.Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/sliderin.png")));
           if(Slide2.isVisible()){
               this.Shop.setVisible(true);
           }

       }
    }//GEN-LAST:event_Slide1MouseClicked

    private void Slide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide2MouseClicked
       this.Slider.setSize(50,480);
       this.Iconos.setVisible(true);
    }//GEN-LAST:event_Slide2MouseClicked

    private void BComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BComprarActionPerformed
        this.PCatalogo.setVisible(true);
        this.Llenar();
    }//GEN-LAST:event_BComprarActionPerformed

    private void Llenar(){
        ResultSet s = null;
        String[] titulos = {"Equipo","Cantidad disponible"};
        model = new DefaultTableModel(null,titulos);
        this.TbCatalogo.setModel(model);
        s = conexion.consultarBD("SELECT*FROM tbl_equipos");
        try {
            while(s.next()){
                System.out.println(s.getString("Nombre_equipo"));
                System.out.println(s.getString("cantidad"));
                Object[] Catalogo = {s.getString("Nombre_equipo"),s.getString("cantidad")};
                model.addRow(Catalogo);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IDECliente1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private void BHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHistorialActionPerformed
        this.PAcerca.setVisible(false);
        this.PCatalogo.setVisible(true);
        
    }//GEN-LAST:event_BHistorialActionPerformed

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        this.PAcerca.setVisible(false);
        this.PCatalogo.setVisible(true);
    }//GEN-LAST:event_BSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDECliente1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDECliente1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BComprar;
    private javax.swing.JButton BHistorial;
    private javax.swing.JButton BSalir;
    private javax.swing.JPanel Historial;
    private javax.swing.JLabel Iconos;
    private javax.swing.JPanel PAcerca;
    private javax.swing.JPanel PCatalogo;
    private javax.swing.JPanel Salir;
    private javax.swing.JPanel Shop;
    private javax.swing.JLabel Slide1;
    private javax.swing.JLabel Slide2;
    private javax.swing.JPanel Slider;
    private javax.swing.JTable TbCatalogo;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tAg;
    private javax.swing.JLabel tAg2;
    // End of variables declaration//GEN-END:variables

}
