/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista_control.iconos;

import Servicios.ConexionDB;
import java.awt.Dimension;
import java.awt.Point;

/**
 *
 * @author AMD RYZEN
 */
public class IDEInicio extends javax.swing.JFrame {

    /**
     * Creates new form IDEInicio
     */
    public IDEInicio() {
        initComponents();
        this.Slider.setSize(50, 480);
        this.Iconos.setVisible(false);
        this.PUsers.setVisible(false);
        this.PAcerca.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Slider = new javax.swing.JPanel();
        Slide2 = new javax.swing.JLabel();
        Slide1 = new javax.swing.JLabel();
        Acerca = new javax.swing.JPanel();
        BAcerca = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cliente = new javax.swing.JPanel();
        BCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Admin = new javax.swing.JPanel();
        BAdmin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tAg2 = new javax.swing.JLabel();
        PUsers = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        psw = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        BIngresar = new javax.swing.JButton();
        tituloin = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Iconos = new javax.swing.JLabel();
        PAcerca = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        tAg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(172, 191, 164));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(172, 191, 164));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Slider.setBackground(new java.awt.Color(11, 32, 53));
        Slider.setMaximumSize(new java.awt.Dimension(250, 480));

        Slide2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide2.setAlignmentY(0.0F);
        Slide2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide2MouseClicked(evt);
            }
        });

        Slide1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/slider.png"))); // NOI18N
        Slide1.setAlignmentY(0.0F);
        Slide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Slide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slide1MouseClicked(evt);
            }
        });

        Acerca.setBackground(new java.awt.Color(133, 14, 74));
        Acerca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BAcerca.setBackground(new java.awt.Color(133, 14, 74));
        BAcerca.setBorder(null);
        BAcerca.setBorderPainted(false);
        BAcerca.setContentAreaFilled(false);
        BAcerca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAcerca.setOpaque(false);
        BAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAcercaActionPerformed(evt);
            }
        });
        Acerca.add(BAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel3.setBackground(new java.awt.Color(133, 14, 74));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_info_white_24dp.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        Acerca.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, 46));

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Acerca de");
        Acerca.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 18, 104, -1));

        Cliente.setBackground(new java.awt.Color(133, 14, 74));
        Cliente.setPreferredSize(new java.awt.Dimension(0, 180));
        Cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BCliente.setBackground(new java.awt.Color(133, 14, 74));
        BCliente.setBorder(null);
        BCliente.setBorderPainted(false);
        BCliente.setContentAreaFilled(false);
        BCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClienteActionPerformed(evt);
            }
        });
        Cliente.add(BCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jLabel4.setBackground(new java.awt.Color(133, 14, 74));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_account_circle_white_24dp.png"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        Cliente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cliente");
        Cliente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 15, 109, -1));

        Admin.setBackground(new java.awt.Color(133, 14, 74));
        Admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BAdmin.setBackground(new java.awt.Color(133, 14, 74));
        BAdmin.setBorder(null);
        BAdmin.setBorderPainted(false);
        BAdmin.setContentAreaFilled(false);
        BAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAdminActionPerformed(evt);
            }
        });
        Admin.add(BAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        jLabel5.setBackground(new java.awt.Color(133, 14, 74));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_manage_accounts_white_24dp.png"))); // NOI18N
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setOpaque(true);
        Admin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 51));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Administrador");
        Admin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 17, 101, -1));

        tAg2.setText("2021");

        javax.swing.GroupLayout SliderLayout = new javax.swing.GroupLayout(Slider);
        Slider.setLayout(SliderLayout);
        SliderLayout.setHorizontalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Acerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Slide1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Slide2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(SliderLayout.createSequentialGroup()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SliderLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(tAg2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SliderLayout.setVerticalGroup(
            SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SliderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SliderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Slide1)
                    .addComponent(Slide2))
                .addGap(31, 31, 31)
                .addComponent(Acerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(tAg2)
                .addGap(32, 32, 32))
        );

        jPanel2.add(Slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 50, 480));

        PUsers.setBackground(new java.awt.Color(133, 14, 74));

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario:");

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña: ");

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        psw.setBackground(new java.awt.Color(255, 255, 255));
        psw.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel1.setBackground(new java.awt.Color(11, 32, 53));

        BIngresar.setBackground(new java.awt.Color(11, 32, 53));
        BIngresar.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        BIngresar.setText("Ingresar");
        BIngresar.setToolTipText("");
        BIngresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BIngresar.setBorderPainted(false);
        BIngresar.setContentAreaFilled(false);
        BIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tituloin.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        tituloin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloin.setText("Bienvenido cliente!");

        javax.swing.GroupLayout PUsersLayout = new javax.swing.GroupLayout(PUsers);
        PUsers.setLayout(PUsersLayout);
        PUsersLayout.setHorizontalGroup(
            PUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUsersLayout.createSequentialGroup()
                .addGroup(PUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PUsersLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(PUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PUsersLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user))
                            .addGroup(PUsersLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PUsersLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PUsersLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(tituloin, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        PUsersLayout.setVerticalGroup(
            PUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUsersLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(tituloin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanel2.add(PUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        jPanel6.setBackground(new java.awt.Color(65, 27, 68));

        jLabel2.setBackground(new java.awt.Color(255, 141, 89));
        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TelStore");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(389, 389, 389))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        Iconos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iconos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/Captura de pantalla 2021-10-17 163124.png"))); // NOI18N
        Iconos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(Iconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 180, 190));

        PAcerca.setBackground(new java.awt.Color(255, 141, 51));
        PAcerca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/outline_info_white_24dp.png"))); // NOI18N
        PAcerca.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 39, 84, 58));

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Programa creado por:");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 115, 510, -1));

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Steven Buritica");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 202, 510, -1));

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nicolas Cedeño");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 247, 510, -1));

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Killiam Puentes");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 292, 510, -1));

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Programacion Aplicada 2021");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PAcerca.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 399, 510, -1));

        jPanel2.add(PAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 680, 480));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/495970.jpg"))); // NOI18N
        jPanel2.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        tAg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tAg.setText("Programacion Aplicada\n");
        tAg.setAlignmentX(0.5F);
        jPanel2.add(tAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Slide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide1MouseClicked
       this.Slider.setSize(230, 480);
       this.Slide2.setLocation(156, 6);
       Dimension sitio = this.Slider.getSize();
//       this.Acerca.setVisible(true);
//       this.Cliente.setVisible(true);
//       this.Admin.setVisible(true);
//       this.tAg.setVisible(true);
//       this.tAg2.setVisible(true);
//       this.Acerca.setLocation(0, 61);
//       this.Cliente.setLocation(0,115);
//       this.Admin.setLocation(0,169);
//       this.tAg.setLocation(6,402);
//       this.tAg2.setLocation(78,434);
        
       if(this.Slider.getSize().height == 480 && this.Slider.getSize().width == 230){
           this.Slide2.setVisible(true);
           this.Slide1.setLocation(6, 6);
           this.Slide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista_control/iconos/iconos/sliderin.png")));
           if(Slide2.isVisible()){
               this.Acerca.setVisible(true);
           }

       }
    }//GEN-LAST:event_Slide1MouseClicked

    private void Slide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slide2MouseClicked
       this.Slider.setSize(50,480);
       this.Iconos.setVisible(true);
//       this.Acerca.setVisible(false);
//       this.Cliente.setVisible(false);
//       this.Admin.setVisible(false);
//       this.tAg.setVisible(false);
//       this.tAg2.setVisible(false);
    }//GEN-LAST:event_Slide2MouseClicked

    private void BAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAcercaActionPerformed
        this.PUsers.setVisible(false);
        this.PAcerca.setVisible(true);
    }//GEN-LAST:event_BAcercaActionPerformed

    private void BClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClienteActionPerformed
        this.PAcerca.setVisible(false);
        this.PUsers.setVisible(true);
        this.tituloin.setText("Bienvenido Cliente");
    }//GEN-LAST:event_BClienteActionPerformed

    private void BAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAdminActionPerformed
        this.PAcerca.setVisible(false);
        this.PUsers.setVisible(true);
        this.tituloin.setText("Bienvenido Administrador");
    }//GEN-LAST:event_BAdminActionPerformed

    private void BIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIngresarActionPerformed
        String Driver = "com.mysql.cj.jdbc.Driver";
        String URL_bd = "jdbc:mysql://localhost:3306/tienda_tel";
        String User = this.user.getText();
        String psw = this.psw.getText();
        DB = new ConexionDB(Driver,URL_bd,User,psw);
    }//GEN-LAST:event_BIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDEInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDEInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDEInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDEInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDEInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acerca;
    private javax.swing.JPanel Admin;
    private javax.swing.JButton BAcerca;
    private javax.swing.JButton BAdmin;
    private javax.swing.JButton BCliente;
    private javax.swing.JButton BIngresar;
    private javax.swing.JPanel Cliente;
    private javax.swing.JLabel Iconos;
    private javax.swing.JPanel PAcerca;
    private javax.swing.JPanel PUsers;
    private javax.swing.JLabel Slide1;
    private javax.swing.JLabel Slide2;
    private javax.swing.JPanel Slider;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField psw;
    private javax.swing.JLabel tAg;
    private javax.swing.JLabel tAg2;
    private javax.swing.JLabel tituloin;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
    private ConexionDB DB = null;
}
